[package]
name = "pacman-core"
version = "0.1.0"
authors = ["djade <djadenkus@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.92", features = ["derive"] }
chrono = "0.4.6"
serde_json = "1.0.39"
log = "0.4.6"
