[package]
name = "pacman-server"
version = "0.1.0"
authors = ["djade <djadenkus@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7.19"
serde = { version = "1.0.92", features = ["derive"] }
